### ISSUE TITLE
AEX (AOSP Extended)

### ISSUE THREAD

**Issue by Spookcity** [Spookcity/ROMS-G800F#11]
Here you can share your experiences with AEX. The ROM is based on AOSP with many "cherry picked" features from other ROM sources.

You can post feedback on [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aospextended-rom-v3-3-t3573531) too,but if it's a test build or you just somehow feel like giving feedback here instead, feel free to do so.

If you're interested in this topic, leave a comment and you'll get automatic email notifications on this.

**Comment by StanNL** [comment]
Email.

**Comment by Spookcity** [comment]
**AEX Changelog** 

**AEX V4.1**
-Android version 7.1.2
-Android security patch April 5,2017
-Merged 7.1.2_r4
-Ticker for music track change
-updated roaming icon hide for new roaming logo in 7.1.2
-Force dialer headsup
-Removed inbuilt Email app
-Seperate Battery style for status bar and qs tile

**AEX V4.0**
-ROM is rebased and done from scratch
-Fixed USB Tethering in settings
-Fixed Adaptable Storage [Not tested by us]
-Fixed Carrier Label Alignment
-Fixed Only 2G in 2nd Sim Slot in dual sim devices
-Fixed Various UI Glitches
-Performance, UI and Battery improvements
-Updated Translations
-Enable/Disable DND during calls
-Removed Privacy Guard and added AppOps
-Simplified Ticker
-Added Slim Recents
-Status Bar Weather
-Fixed Crash issue in storage manager app
-Update interfacer
-Add Missing OMS stuff
-Update Our Default Wall
-Remove FP Settings on a Non-FP device
-Enable/Disable Power Menu on lockscreen
-Dynamic Location Tile
-Compass tile
-CPU Info
-Alarms Blocker
-Clock Date Customisations
-Removed CM 11 Music Player
-Added Phonograph
-Replace Slimperience with via browser
-Battery status on ambient display
-Dash charging info on lockscreen(op3/3t)
-More circular icons
-Toggle Battery saver warning color
-Hide Roaming icon from statusbar
-DUI music control buttons
-Bluetooth Headset battery status
-Screenshot crop and share
-On the go mode
-Added our wallpaper's gallery link to about us

**Comment by Oleggluk** [comment]
AEX firmware is very similar to the RR firmware, but what's the point in it? Settings are less than in RR, a few graphical changes and everything. (Google Translate)

**Comment by Spookcity** [comment]
@Oleggluk Yeah,I'm unsure. There is something about RR that never really did it for me. I can't explain it. I'm just not a giant fan of it. I do really really like AEX though. Perhaps I need to give RR another shot and see if I feel the same about it.

**Comment by AndiVR46** [comment]
i tested AEX 4.1 now for some hours...

1. Because magisk in this build changes the SELinux to enforcing Firefox didn't work from the beginning
2. Via browser has been working for some hours, bur recently crashes after some reboots.
3. bluetooth transfers (.apk) from pc to handy fail, doesn't start the transfer, but askes for confirmation...
4. question: is the first left page (homepage) in this ROM not changeable? How to get away the Google tile/widget and the date from 1st page? - i'm no Google fan, i just use the pico GApps package... the button has no function so...
 
![screenshot_20170423-122136](https://cloud.githubusercontent.com/assets/27836686/25313771/adbcf752-2835-11e7-814e-4199c4bddf04.png)
![screenshot_20170423-122155](https://cloud.githubusercontent.com/assets/27836686/25313773/adc25c9c-2835-11e7-8cf3-c3abd3a53c23.png)
![screenshot_20170423-141628](https://cloud.githubusercontent.com/assets/27836686/25313772/adbe418e-2835-11e7-971a-4de1629e1866.png)

**Comment by Spookcity** [comment]
@AndiVR46 I didn't realize magisk changed SELinux to enforcing. I have only used via browser so far with v4.1,but have not had any problems with it over the course of a couple of days. I'm not sure what would be causing that problem for you.

I haven't tried BT transfer. It is possible that it may be broken in the ROM. I'm not sure why it would be,but it's def possible. Something I will need to look into.

The Google thing on the homescreen bothers me some too. I don't think you can do much about it...except switch launchers as AEX is using pixel launcher,so yeah that kinda explains the non removable Google app thing.

**Comment by AndiVR46** [comment]
hmm,ok... and the non changeable first left page? Have been using HD Widgets since years on the first page. i've done nothing with Via, after some maybe 3-4 reboots it gave me the last pic... The Google thing is excuseable ;)

**Comment by Spookcity** [comment]
Yeah, it doesn't seem like you can change the left page,or which page to use as your home screen at all that I could find. While I don't mind pixel launcher, when I decide to use a ROM for any length of time I always install Nova launcher. This solves all of those issues for me.

Weird about the "webview not being installed properly" message. I suppose there was some issue with the build or some repo that caused this. It can be installed from the play store if it's causing issues though.

**Comment by AndiVR46** [comment]
already done, but no success... Via crashes again... Just wanted to let you know ;)

**Comment by Spookcity** [comment]
Interesting. I'm at a loss. I haven't had any problems with it. Thanks for letting me know though. I'll continue to use via and see if I get the same problem.

**Comment by AndiVR46** [comment]
ok that... I've known the browser problem in LOS already when using Magisk and the resulting SELinux state change. there i used FF, Gello, Gello Mod from XDA... the state sometimes changed not after first reboot, but the 2nd time it does... take your time, a bit pity actually, but BIG THX anyway 
![screenshot_20170423-160924](https://cloud.githubusercontent.com/assets/27836686/25314194/7d89da50-283f-11e7-878b-cc524ac397b4.png)

**Comment by Spookcity** [comment]
I really had no idea that magisk changed the SELinux state at all. That is good to know. SELinux is still actively being worked on for our device. Along with hopefully a safteynet fix. While I am not currently messing with it,I know the other devs have looked into it and would like to find a fix for this.

**Comment by ghost** [comment]
@Spookcity Could you do something for me?
- Create an issue
- Comment on that issue
- Close that issue

The text doesn't have to be anything special, just 'test' would be enough.

Thanks in advance. (By the way, anyone could do this, not just spook)

**Comment by Spookcity** [comment]
@StanNL done. I did all 3 kinda quick. I hope that's OK. Let me know if not.

Also,I will try to help out some with the ROM comparisons when I have some time.

**Comment by ghost** [comment]
@Spookcity That's great, thanks! The ROM comparison does take up a lot of time indeed. I'm doing it piece by piece right now.

Those tests were in order to confirm something I already expected. You don't have to leave a comment on an issue in order to subscribe, as long as you are watching the repository! I'm removing the paragraphs where I mentioned the subscription thing.

**Comment by Spookcity** [comment]
@StanNL Ahh OK. Sounds good to me. I would imagine the ROM comparisons indeed take a bit of time. I can't say when, but I will try to do a couple. Although you're better at describing and writing these things than I am...and English is my only language. I'm not real sure what that says about me lol

**Comment by ghost** [comment]
@Spookcity Thank you! I am participating in Cambridge English exams, so I'm practicing writing a lot. Don't worry ;)
Also: if you've spotted any mistakes, please tell me since I'm still learning.

As for the writing of the texts themselves: it's fine if you just send me a list of features one day and I'll turn it into a text for you.

**Comment by Spookcity** [comment]
@StanNL Well the exams are certainly working! I would never in a million years guess that English is not your native language. Hopefully one day I'll stop being so lazy and become half as good in your native tongue as you are in mine. :)

I will at the very least get you a list of features and what-not about some ROMS in the very near future.

**Comment by ghost** [comment]
@Spookcity
> Well the exams are certainly working! I would never in a million years guess that English is not your native language.

Really? Thanks a lot! If I score 80% or higher on the exam, I will get a C2 certificate, which indicates that I indeed speak English at a near-native level. However, this isn't just a standard English test ;)

> Hopefully one day I'll stop being so lazy and become half as good in your native tongue as you are in mine. :)

I'm sure you'll be able to do it! Dutch is one of the most closely related languages to English. However, like any language, it takes a lot of time and you're already doing the most important step, which is hearing and listening to Dutch speakers! (Unless you don't come out of your basement and sit behind the computer all day...)

> I will at the very least get you a list of features and what-not about some ROMS in the very near future.

That would be great! Take all the time you need.

**Comment by Spookcity** [comment]
@StanNL I would guess you will do very well on your test. Good luck either way!

I do spend far too much time on my computer,but I do hear plenty of Dutch. I watch and enjoy de wereld draait door most nights :D
I understand far more Dutch than I'm able to speak for sure.

Either way,back on topic hehe
I will most definitely get you a list of info and features on a couple of ROMS in the next couple of days.

**Comment by AshVo925** [comment]
The Android system webview updated for me since flashing pico Gapps and I dont have any error with it,so far.. I use Jet audio for music and it's just giving me a strange error msg 
(libJYt:so text relocation
 libJM4R:so text relocation) yet everything works fine,first time I got that I think it has something to do with lyrics though but it's cool.. I always use jet audio and this is the first time an error,perhaps the restoration through TB,app only not data messed up?
Android6 to 7 data may be incompatible so I rarely would do that,besides I encrypted the data and forgot the key so yeah,snap camera finally fully HD video all work perfect

**Comment by ghost** [comment]
@AshVo925 What is the file extension of the song file name?

**Comment by ghost** [comment]
@AshVo925 And: When does the error occur? When opening the app or whilst playing​ the song?

**Comment by AshVo925** [comment]
The error occurs as I open the app,then disappears but I took a screenshot,I'm unsure how to take a logcat but what I typed was pretty much what goes on,oh thanks and you're welcome man,glad to be here

**Comment by AshVo925** [comment]
File extensions are mp3 format btw

**Comment by ghost** [comment]
@AshVo925 Well, if you don't know how to send logcats (which is fine), there isn't much we can do. However, a way to "fix" this, and that is by installing a different music app. I would recommend Phonograph.

Hopefully we'll be able to fix this one day, but for now, this is all we can do.

**Comment by Spookcity** [comment]
@AshVo925 Yeah a log would help,but no problem. I'm unsure what is causing the error you mentioned. If it's not causing any issues I wouldn't worry too much about it though. 
Or as @StanNL mentioned perhaps try another music player just to test.

**Comment by AshVo925** [comment]
How do I take a logcat and I said it isn't an issue I was just curious to that error msg coz I haven't got it since I've had a droid,that's my music app.. I have plenty time to learn

**Comment by Spookcity** [comment]
@AshVo925 Well,if you use Linux and have sdk/adb setup you can connect your phone to your PC with adb enabled in developer options.  Then open a terminal and  type "adb logcat > logcat.txt" without the quotes. 
If not and probably the easiest way is to just download Matlog from the playstore and use that. 
Edit: Also,if you go the terminal way, ctr+c to stop the log.

**Comment by AshVo925** [comment]
Phonograph works perfectly but I like super customized equalizer settings,that's all,thanks again

**Comment by AshVo925** [comment]
PC is broken that's my issue,can't really do much to my phone coz I'm wary of losing everything you see,I will get matlog now,thanks guys,IL come back when I have a real problem😅

**Comment by ghost** [comment]
@Spookcity That's also exactly how it works on Windows haha

**Comment by Spookcity** [comment]
@StanNL Interesting,I had no idea it was the same. I guess windows ain't all bad
 :-D

**Comment by ghost** [comment]
@Spookcity Every platform has its (dis)advantages ;)

**Comment by AshVo925** [comment]
Matlog is so informative I felt like I was tripping reading all that information.. will update my story after a nap,I really love this rom,it is perfect and I don't need Xposed as much as i thought I would..

**Comment by AshVo925** [comment]
04-27 12:41:15.572 W/linker  (19806): /data/app/com.jetappfactory.jetaudioplus-1/lib/arm/libJY2.so has text relocations. This is wasting memory and prevents security hardening. Please fix.)
Can I manually edit them via a terminal and "fix"

**Comment by Spookcity** [comment]
@AshVo925 There is nothing you can do about this warning to my knowledge as it is a problem with the build of your audio player app. So unless it's an open source app and you can and are willing to compile it yourself I don't think you can do much.
I wouldn't worry too much about it though honestly.

**Comment by AshVo925** [comment]
OK thanks,its working fine,just that error msg was new to me.. Phonograph isn't that bad either hey,is it safe to remove along with the equalizer,neither work nor does pulse,without damaging any sound libs or things like that?

**Comment by Spookcity** [comment]
@AshVo925 Well, I don't want to say something and then have you lose stuff on your phone, so as long as you have a backup my answer would be that 
I would think that these could be removed without issue, but again,I'm not 
100%

**Comment by AshVo925** [comment]
They cool I froze them coz I'd rather keep em instead of interfering with your ROM.. thanks bro you're awesome

**Comment by Spookcity** [comment]
@AshVo925 Haha,thanks man! 
Freezing them was probably the best way to go.

**Comment by AshVo925** [comment]
Hey the magisk installer for those sound effects offered had me bootloop,luckily I restored a backup,don't know if it's coz I flashed 3 zips but didn't bother with dalvik wipe coz I was I'm a hurry lol OK games are better than on any other ROM for me,this the best,just be careful with flashing your own stuff outta nowhere,
Sorry
Thanks

**Comment by Spookcity** [comment]
@AshVo925 Yeah,if you're talking about Magisk modules,that's something I've not really looked into. I'm fairly new to Magisk in generally honestly and am just now starting to learn more about it.

**Comment by AshVo925** [comment]
Magisk caused a few problems for me so I finally got a ROM to work and since spook had a hand in it I'm keeping it,though magisk is a danger zone given my experience on this ROM..

**Comment by Spookcity** [comment]
Yeah, I have not really messed with Magisk much at all aside from just using it as root. I haven't messed with modules or whatever else at this point. Maybe one day I'll jump in and see how badly I can mess things up :D

**Comment by Guntzog** [comment]
I think am Gina stick to this ROM,  the best for me, GJ @Spookcity  🥇

**Comment by Spookcity** [comment]
@Guntzog This is probably my favourite ROM. There's just something about it. I'm going to try to update it to v4.2 sometime this week.

**Comment by Guntzog** [comment]
That would be grate, the only bad thing is that gogogle anim x) expect that it's my favorite too

**Comment by Guntzog** [comment]
I activated battery saver yesterday with 20%, I woke up and it's still 20% ! 
This became my favorite too. Waiting for uptade @Spookcity you van add features?

**Comment by Spookcity** [comment]
Technically,most features can be added by cherry picking the needed commits. Some are easy and some much more difficult. I built a very customized version of slim 6 with optimized toolchains and added apps etc. I am still planning on doing this for a nougat ROM as well. I've just been trying to decide between AEX and slim 7.

**Comment by Guntzog** [comment]
If can I request features: controlling hw buttons light and commands :)

**Comment by Spookcity** [comment]
I am just going to build the "standard" ROM this time around. Perhaps they have even added such a feature in v4.2. If not I will look into that for a future build.

**Comment by Spookcity** [comment]
**AEX Changelog**

**AEX V4.2**

- Merged May Patch 7.1.2_r8
- Updated Packages and Translations
- Updated pre-built APKs
- AEXPapers is back
- New AEX OTA
- Droped Lock Clock
- Switched to OmniJaws
- CAF Sound Recorder
- Keyguard Status Bar clock and Weather
- Nav Bar Button Tint
- Improve​d Screen Pinning
- SystemUI Restart
- Updated Sounds
- Processor Info in about phone
- Kernel Enforcing and Permissive info in about phone
- Fixed Gap after removing QSTiles
- Custom settings for Power Plug Disconnect and Connect
- Tile for HW keys Enable/Disable
- Center lockscreen shortcuts
- Removed stausbar Ticker fade animation
- Fixed Swaped nightlight brightness
- Extensions QS Tile
- System App Remover
-Grid Recents UI 
- Update OMS Commits
- Fixed mismatched fonts in Lockscreen Status Bar Clock
- Updated MusicFX with DSP Modes 
- Fixed Bluetooth Receiving issue
- Performance enchancements and bug fixes

**Comment by Spookcity** [comment]
**AEX Changelog**

**AEX V4.3**

- June security patch 7.1.2_r17 merge
- Remove pixel icons
- Add MicroG support
- Improve AEX settings header
- Add AEX platlogo
- Add AEX settings drawer header
- Add new #BeExtended headers
- Fix battery icon theming
- Update OMS commits
- Rootless SystemUI restart
- Use more vectorized icon
- Add lockscreen pattern grid size
- Screen pinning option in Grid recents UI
- Recents task locking
- Fix navigation bar always showing on the left
- Fix various NPEs
- Add AOSPA Optimisations
- Add Xbox key layout
- Volume key cursor control
- Option to enable/disable home key during incoming call
- Improve expanded desktop QS tile
- Add support for sensitive numbers
- Silent mode is back
- Update pre-built APKs
- Update all packages
- Update translations
- Performance enhancements and bug fixes﻿

**Comment by Spookcity** [comment]
**AEX Changelog**

**AEX V4.5**

- Merge August security patch
- Merge latest CAF Tag in respective repos
- Add support for Snapdragon LLVM toolchain (SDClang)
- Add support for boost framework
- Add support for fling velocities
- Enable/Disable kill button on notification guts
- Improve SlimRecents
- Fix string derps
- Fix In-Call vibrations
- Animate icon while locking a task
- Fix Lockscreen shortcut icons disappearing after reboot
- Make button long press delay configurable in SmartBar
- Fix layout of system header
- Fix task lock and free form button placement
- Fix Dex2oat
- Fix In-Call timer bug
- Fix reloading of theme in AEX OTA
- Fix theme issues in screen pinning mode
- Disable home button wake on devices with sensitive HW buttons
- Add Paranoid Android Pie controls
- Add check for accidental touch
- Add pocket lock and pocket judge
- Doze Service: Fallback to tilt sensor as pickup sensor for ambient display
- Fix many memory leaks
- Option to block sensor for certain packages
- Fix few NPEs
- Increase sensitive numbers support
- Update all translations
- Update AEX Papers
- Update all pre-built packages
- Performance enhancements and bug fixes

**AEX V4.4**

- Merge July security patch
- Merge upstream commits from CAF
- Fix launch of music player on headset connect after reboot
- Music player on headset connect: Add bluetooth compatibility
- Add safe headset volume option
- Optimise HWUI
- Switch to Chromium webview
- Fix wrong peek height of notification panel
- Speed up fingerprint wakeup and unlock scenario
- Fix camera shutter sound toggle
- Fix many random crashes
- Add HW home button wake
- Improve night mode
- Improve QS tiles
- Add ADB Over Network support and QS tile
- Fix network arrows not showing when data save was enabled
- Fix various NPEs
- Fix memory leaks and errors
- Switch to Launcer3 (Pixel UI + Icon pack support)
- Change internal shared storage icon progress bar accent
- Add boot option in AppOps
- Add new smart bar icons
- Add left navigation bar pulse support
- Fix memory corruption on sound trigger
- Option to display disabled data indicator icons
- Add option to enable button backlight only when the button is pressed
- Set GBoard theme to pixel by default
- AEX OTA is completely themable now
- Add support for Crowdin
- Fix icon themeing on Valerie and few more themes
- Fix hiding of developer options
- Fix smartbar DPI updation
- Update all translations
- Update all pre-built packages
- Update AEXPapers
- Update all source-built packages
- Bug fixes and performance improvements

**Comment by Spookcity** [comment]
**AEX Changelog**

**AEX V4.6** FINAL

- Merge September security patch
- Merge latest AOSP Tag
- Merge latest CAF Tag in respective repos
- New AospExtended bootanimation
(Credits:https://plus.google.com/+ManuelMöllmann)
- Fixed adaptable storage
- Fix memory leaks
- Add support for more boost frameworks from Paranoid Android
- Improve fingerprint scanner performance
- Allow user to add or remove QS tiles with one click
- DUI: Support for left  landscape navbar
- DUI: Migrate from broadcasts to API for some action handling 
- Fix few NPEs
- Update all translations
- Update AEX Papers
- Update all pre-built packages
- Performance enhancements and bug fixes
