### ISSUE TITLE
Personalization Discussion

### ISSUE THREAD

**Issue by ghost** [Spookcity/ROMS-G800F#13]
Here you can ask anything about everything! As long as it has to do with Android, you can ask practically anything.

**Comment by ghost** [comment]
To get this discussion started, I was wondering:

1. Which email app are you guys using?
2. What music app would you recommend?
3. How long is your SoT on average?
4. Which ROM are you using and why?
5. Are you using a GitHub app and if so, which one?


__My preferences__ 
1. Inbox by Gmail
2. Phonograph
3. I'd say about 4.5 hours
4. XOSP, because it's extremely fluid, especially with L Speed
5. FastHub

**Comment by AndiVR46** [comment]
Hi, first of all - great idea from you @Spookcity and @StanNL ! ;)
I'd like to ask which OMS capable 7.1.2 ROM do you suggest?
discussion - later... ;) i think i'll test the Kernel also... BIG THX

**Comment by Spookcity** [comment]
1.Email - Aquamail
2. Music player - BlackPlayer Ex,although phonograph is now included in AEX and I must say its very nice.
3. SoT - hmm,tough one. Probably 4-5 hrs
4. ROM - AEX : Just testing currently. I switch ROMS a lot,but it is probably my favorite N ROM currently.
5. Github app - FastHub now thanks to @StanNL. It seems to be a really great app indeed.

**Comment by Spookcity** [comment]
@AndiVR46 I am using AEX 4.1. It is fully OMS capable and I've added the latest substratum app to the build. I think its a great ROM. Beanstalk is also really nice if you want a more LOS 14.1 with OMS and other additional features. Its still 7.1.1 though I think. I'm gonna try to build an update soon.

**Comment by ghost** [comment]
@AndiVR46 Yeah I agree with @Spookcity on this. I haven't tested out AEX for a long period of time, but I did use it for a day or two and I can definitely recommend it.

By the way: This question would fall into the _Questions about ROMs_  category, not that it really matters.

**Comment by Spookcity** [comment]
@AndiVR46  Also,just to make sure I don't take too much credit,this whole idea was @StanNL and he set it all up. So HUGE credit goes to him!

**Comment by ghost** [comment]
@Spookcity Well I only came up with the idea and it's up to everyone else to share their creations, because without you, this wouldn't take off!

**Comment by Spookcity** [comment]
Yeah,hopefully others will join in on the discussions and even share their creations.

**Comment by Oleggluk** [comment]
1. Mail.Ru
2. AIMP
3. Difficulties of translation
4. RESURRECTION REMIX N . Used all available firmware versions. RR is the most stable, good translation, a lot of settings (no need for xposed). I'm really looking forward to version 5.8.3 (google translation)
5. ----

**Comment by Spookcity** [comment]
@Oleggluk Thanks for joining in!
I promise to try my best to update RR for you if Zocker doesn't. It's all a matter of time and I just have a lot going on currently.

**Comment by AndiVR46** [comment]
1. Blue Mail
2. Poweramp
3. ... i never played 4-5 hrs at once
4. LOS 14.1 before, now testing AEX 4.1
5. nope
@Spookcity - yeahh, i recognized he has done/helped you with the GH thing. also BIG THX to
 you @StanNL

**Comment by ghost** [comment]
Which browser do you use?

**Comment by Spookcity** [comment]
I generally use Chrome Dev

**Comment by Mikahlo** [comment]
About launchers: did you ever heard of [KISS?](https://github.com/Neamar/KISS)
On Lineage OS, this one was my favourite. The launcher allows you to hide apps, to tag them for the search function and a nice little feature to force close apps is integrated too. It`s a very lightweight one, so this should be the max performance you can get from a launcher.
Regarding a music app: I can recommend  [Odyssey](https://github.com/gateship-one/odyssey) or [vanilla](https://github.com/vanilla-music/vanilla).

**Comment by Spookcity** [comment]
I have heard of,but have not used KISS launcher. I'll have to give it a try. I have been messing around with [this](https://forum.xda-developers.com/android/apps-games/t-ui-terminal-console-launcher-t3146288) recently and rather enjoy it.

**Comment by Mikahlo** [comment]
Today I wanted to update TWRP to version 3.1.0-0 and got an error "not a directory". I searched a bit and couldn't find any posts about it. So I did a workaround and installed the TWRP app. With this app I was able to update successfully. Just wanted to share that.
@Spookcity : I tried the console launcher myself because I was curious. Turns out that this thing is nice but impractical for usage on the go with one hand.

**Comment by Spookcity** [comment]
@Mikahlo Good to know. Thanks!
And I agree that the console launcher is not that practical for daily use. I just have it to play around with mostly. Always Nova for me.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Guntzog** [comment]
Does anyone know why do I always get this error when I try to restore a backup?
Restore from 7.1.2 to 7.1.2 using twrp 3.0.0

![screenshot_2017-06-15-02-00-11](https://user-images.githubusercontent.com/28767865/27212304-557d0290-525f-11e7-8b96-e1667f7ecf61.png)




_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@Guntzog I have no clue,sorry. Hopefully someone else will.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@Guntzog Do you have enough storage space left?

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Guntzog Update TWRP https://forum.xda-developers.com/showpost.php?p=72685083&postcount=1011

**Comment by Guntzog** [comment]
@StanNL yep, OK @oleggluk I'll try that

Edit : @Oleggluk i get the same error with 3.1.0 and 3.1.1 when try to restore a backup, and I get this error when I try to flash any ROM via 3.1.1, any idea s guys ? I feel Like my phone is cursed ! 
![screenshot_2017-06-16-08-58-11](https://user-images.githubusercontent.com/28767865/27246833-a7a7158e-52f4-11e7-850f-491c95ab61c3.png)


![screenshot_2017-06-16-09-30-22](https://user-images.githubusercontent.com/28767865/27246860-c7691b1a-52f4-11e7-9019-9f95e72a826a.png)

![screenshot_2017-06-16-08-56-11](https://user-images.githubusercontent.com/28767865/27246837-b1b25e76-52f4-11e7-89d6-51b919346486.png)

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
