### ISSUE TITLE
Test Builds #3

### ISSUE THREAD

**Issue by ghost** [Spookcity/ROMS-G800F#19]
This is a continuation of #10 and #18 about 'test builds'.

**Comment by ghost** [comment]
Maybe github should use like a page-layout, that would save me a lot of scrolling. I hope you don't mind moving the conversation all the time

**Comment by Spookcity** [comment]
OK,1.8 I get the boot animation.......Now the keypad...Then it locks up and reboots.
If you wish to try to flash this and  the try test14 please be careful. I would feel really bad if this destroys anyones phone
Download [Test15](https://drive.google.com/open?id=0B_rGv18gTmnVa3FKQWc1MXFZaUE)

And @StanNL  I don't mind at all

**Comment by ghost** [comment]
@Spookcity I'm a bit doubtful as to whether or not I should install this.. I think I'm just going to stay on 1.6 and if you manage to get a 1.65 build I'll try it out because I don't want to break my phone... Maybe someone else dares to try this out, but I don't think I will

**Comment by Spookcity** [comment]
@StanNL I completely understand. I also think that it is very unlikely that this has anything to do with it. I'm building a 1.65 again. Maybe it will boot. If so Ill post it up. If not I just don't know. Hopefully Ill get feedback on XDA. Then I may,if I have time,later today remove all of the revision checks within the CPU files. Maybe this matters. Why,no idea. Then I guess I'll try to figure out how to stop the phone from booting at 1.7.

**Comment by Oleggluk** [comment]
@Spookcity Test 15. Smoke, hiss, explosion. Knocked out the windows. The cat jumped from the 9th floor. The dog made a big pile ...))) Joke.
Not booted. Hangs on the Samsung screensaver.
I returned to test 14, no changes, just hangs on the desktop and reboots.

**Comment by Spookcity** [comment]
@Oleggluk Haha..Whew,you scared me there after only reading the first line! Kinda figured it wouldn't matter,but thanks for risking your phone and trying. At least that's knocked off the list. 

Edit:
Also strange to me how it hangs on the Samsung logo for you fot test15,but I'm able to get t he bootanimation and even get to my desktop.

Edit II: Again I built 1.65. It boots for me and works for a short time t hen just locks up. I leave it here because others,as we see,may experience different.
Download [1.65](https://drive.google.com/open?id=0B_rGv18gTmnVYVlLTGhkOXBVRjg)

I'm off for now. Let me know about the 1.65. I will try to mess with it more and remove the revisions checks a bit later if I have time.

**Comment by Oleggluk** [comment]
@Spookcity I dont know. You have a military prototype Galaxy S5 Mini)). . I installed test 10 again, also no changes.
I installed the test 15 again, the samsung screen saver is not loaded. I think it's easier to stop at 1600, otherwise it takes a long time.

**Comment by Spookcity** [comment]
@Oleggluk Haha,something I just don't understand. I agree its probably best to just leave it at 1.6 and be done with it,but my brain won't let me lol I must understand how this is possible.
Did you try the 1.65 OC I posted above?

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity Test 16 also hangs on the desktop.

**Comment by Spookcity** [comment]
@Oleggluk Thanks. I'm kinda of glad for this as if it worked for you and not me it would have made an already very confusing situation even more confusing. Iv'e lowed the voltage and am building 1.7 again. Although why this would matter I also don't know as its the same on the 1.6,but..

**Comment by ghost** [comment]
Test 16 also didn't work for me

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
[test17](https://drive.google.com/open?id=0B_rGv18gTmnVU3NhYlBEc0EtdHc) - Reset voltages back to stock values.

**Comment by ghost** [comment]
@Spookcity I can't download it. Did you delete it?

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
Hmm,not intentionally. I think its right,but maybe [This](https://drive.google.com/open?id=0B_rGv18gTmnVU3NhYlBEc0EtdHc)
Edit: Yep the first was the wrong link errr. Corrected

**Comment by ghost** [comment]
By the way: The boot.img you uploaded &mdash; was that just the stock kernel with a different clock speed, or was it your kernel with another clock speed? Because if it's just the stock kernel with a different clock speed, that would indicate that my phone just cannot handle it.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@StanNL It was my kernel.No difference apart from all of the tests on here,just decided to try to rule out it being relateed to anykernel2
Although,that is another thing to try. Given time I will just OC the stock kernel and see. Building one now with all of the revision checks removed.

**Comment by Oleggluk** [comment]
@Spookcity Test 17 as well as before, no change. freezes on the loading animation.

After the second reboot hovered on the desktop.

**Comment by Spookcity** [comment]
Thanks @Oleggluk I'm going to build this version without revision checks. Then I will try to just OC the stock kernel. After that...No idea.

**Comment by Spookcity** [comment]
[Test18](https://drive.google.com/open?id=0B_rGv18gTmnVZEJONDRmUGEtZUU) -Revision check removed

**Comment by ghost** [comment]
I'm sorry but this doesn't work either...

**Comment by Oleggluk** [comment]
@Spookcity Test 18 is no change.

**Comment by Spookcity** [comment]
Haha,oh my god. My brain is gonna explode. I am building a stock kernel from the device repo (cm-3470) Only OC'ed to 1.7.I'll post it in a few. If this doesn't work I have no idea....If it does I don't really either though haha. No I would have to guess it would be a build flag in my makefile perhaps,but still,that'd be weird. I'll wait and see what  this test brings before I start thinking ahead.

**Comment by ghost** [comment]
Yeah but if it would be a build flag, why would it work for you then? That wouldn't explain it either, but I'll just keep on testing...

**Comment by Spookcity** [comment]
@StanNL Yep,I completely agree,but I'm at a point now where none of this makes any sense to me,so I just don't know. I also cant get the stock kernel to build with my toolchain and its throwing erors,err

**Comment by ghost** [comment]
Well, I think we've ran out of ideas. You mentioned something about booting the device at a lower clock speed, right? Maybe that's another possibility

**Comment by Oleggluk** [comment]
Ahahah, After kernel test18, kernel backup does not help. The phone does not load, the eternal animation of the download.

**Comment by ghost** [comment]
@Oleggluk That's odd, are you sure you're installing the right one? I always go back to test13 and it worked for me

**Comment by Spookcity** [comment]
@Oleggluk  Wait,your phone works still though right?? Uhgg This should def not have caused this
@StanNL Yes,this is the last idea I have, Lower the clock speed on boot. Im just unsure how.

[Test19](https://drive.google.com/open?id=0B_rGv18gTmnVWlE5eGFWYVhGeW8) Stock kernel with stock toolchain. No build flags,all stock except a 1.7 OC
Goes without saying,but...It works for me lol

**Comment by Oleggluk** [comment]
I restored today's backup, the phone does not load, eternal animation. I restored a two-day kernel backup, the phone does not boot, eternal animation. I asked Test13, the phone does not load, the eternal animation)).
Now I'll try to flash the stock boot.img from the firmware.

**Comment by Spookcity** [comment]
@Oleggluk Oh my god man. I so hope that works. I'm very sorry. I feel really bad. There was certainly nothing in test18 that should have caused this.

**Comment by Oleggluk** [comment]
Stock boot.img also did not help. Eternal animation. I'm going to flash the smartphone.
Spookcity, do not worry. I volunteered to test myself. And I will continue))

**Comment by Spookcity** [comment]
@Oleggluk I know,but I still feel really bad. I'm only trying to help people and improve the phone a little. I definitely didn't want to cause this :(
I really hope that will work. I'm very unsure why that kernel would have caused this. I made no big changes. DJSteve also removed the revision check from his kernel. I doubled checked just to make sure it would be OK.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Mikahlo** [comment]
Test19 didn't boot for me. The boot animation got stuck. The log I made is useless.
So we all have the same phone even the revision is the same. But what's different?

**Comment by ghost** [comment]
@Mikahlo I'm not sure, but @Spookcity mentioned something about the fact that he has Fusing Speed Group 8, while you have Group 6, but I have no idea what that means, how to change it, and even if it's possible to change it or if it's just a hardware difference

**Comment by ghost** [comment]
I don't have much time today (nor the upcoming two weeks, why am I even doing this at the moment?) but here are the only 295 about those groups (just in case you don't know how Google's syntax works): https://www.google.nl/search?q=%22fusing+speed+group%22

**Comment by Spookcity** [comment]
@StanNL Yeah, I'm going to look into what fusing speed is exactly. I did some searching yesterday,but found no useful info.
So the stock kernel 1.7 OC still doesn't work for anyone here but me
It has to be a HW difference then,no?
But what and why? So frustrating.
@Oleggluk  What's the situation with your phone?

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
Installed the firmware, without deleting data, does not work, eternal animation. That's bad. Found a full backup five days ago. I did all the wipe and restored the backup. The phone started. I did not lose much., But it's long minutes for me, I've had 5 cigarettes). For today, enough experiments))

**Comment by Spookcity** [comment]
@Oleggluk Oh man, I'm so glad it's working at least. Again,I'm very sorry that you lost stuff and had to go through this. Whew,I'm just glad its not broken. Yet another confusing thing that makes no sense to me though. No idea what caused that for you. 

Edit:
This issue that @Oleggluk had also seems to indicate a possible hardware difference. Again,but why I wonder. 

Edit II:
@StanNL Those search result are pretty much what I was looking at yesterday. I'll look a little deeper, but didn't see anything very helpful.
At the end of the day I may just have to assume that I have a super S5 mini and contribute all of this to that... Only so I can stop thinking about it and sleep tonight lol

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Mikahlo** [comment]
Found this > [link](https://lwn.net/Articles/566221/). So the voltages needed for some cpu steps are different depending on the asv group I guess.

**Comment by Spookcity** [comment]
@Mikahlo Great job! This makes a lot of sense actually. If your voltage steps are different then mine, it would explain a lot. Although I still don't get why they are different.
I was thinking,I believe when I posted the test version with the stock voltages that I actually forgot to change them in a file. I will try to do that later or tomorrow and post up test 6318 lol
Otherwise I'll look more into that link,but now knowing its voltage related explains a little. 
Interesting:
”ASV group gets fussed on SoCs during process of mass production.”


_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
That sure is a nice find. Hopefully it'll help because I was completely clueless

**Comment by ghost** [comment]
My CPU cores seem to have their own will. No matter which minimal and maximal frequencies I choose, it always slowly goes back to 800 MHz, which is strange. Am I using the wrong governor? I'm using _userspace_ at the moment

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@StanNL perhaps,I have actually removed userspace from my newer builds. I can place it back though if you prefer. I have never used it and am a bit unsure of how it behaves. If your frequency stays at 800 MHZ even with say zzmoove then something is not right for sure.

Edit:
I am building my last build for today..and very possibly regarding this issue (unless I can sort out how to have it boot lower than the max) This will be for SURE the stock voltages. After that I give up and have to assume,for the sake of my sanity,that it has to do with the set fusing speed. Although this will always be strange to me.

**Comment by ghost** [comment]
@Spookcity Well userspace is known for allowing the user to set their own clock speeds, so I thought that would be the best choice. I'll try zzmove

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
Even with the performance governor, it still goes to 800 (though it should always stay at the max frequency then). In that case I'll use zzmoove indeed, though it keeps disabling certain cores.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
Download [Test20 - Stock voltages](https://drive.google.com/open?id=0B_rGv18gTmnVMFdkY2piMEtPeEE)
That's all I got for today. My hopes are low and if it doesnt work then I'll just keep the 1.7 for myself and share the 1.6 only. Thanks everyone for testing!


@StanNL very strange.My frequencies stay at 1000 on userspace and full on performance.I am using the 1.7 build though,so perhaps this is why. I'm unsure

**Comment by ghost** [comment]
@Spookcity I have to disappoint you, because test20 still does not work for me :(

**Comment by Spookcity** [comment]
@StanNL Hah,not surprised. I just don't know. It's a shame because the 1.7 does run nice,well for me. Oh well. I'll still try to look into the boot CPU frequency. Other then that,1.6 it is I guess. This will always be a big mystery to me.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@Spookcity It definitely is. Maybe henny has some time today, since he just posted something on XDA

**Comment by tester-02** [comment]
Sadly a bootloop for me with test20. it doesn't even get to the homescreen. I'll try to get a log.

**Comment by Spookcity** [comment]
@tester-02 Thanks! I'm running test20 and typing from it now. No surprise though. All of these versions have worked for me

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@Spookcity It just doesn't make any sense... Are you sure you're using a Galaxy S5 mini?

**Comment by Spookcity** [comment]
![](http://i.imgur.com/b5A3JyQ.png)


_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@Spookcity Just to make sure...

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Mikahlo** [comment]
Test20 boots and works for me. I didn't [threw it on the ground](https://www.youtube.com/watch?v=gAYL5H46QnQ) :D 
Just have to test if the 1.7 ever gets reached.

**Comment by Spookcity** [comment]
@Mikahlo what? Crazy and more confusing! Please keep me posted 

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@Mikahlo Really? Wow! Maybe I did something wrong... I'll try installing test 20 again then.

**Edit**
The craziest thing ever just happened... It booted (like it always did), but when it was about to freeze (I think) it started vibrating like crazy!! And then it rebooted again and it froze, like it has done 12 times now today, and has become 'normal' behaviour now.
Maybe I just got called without getting a popup or anything

**Comment by StanNL** [comment]
The craziest thing ever just happened... It booted (like it always did), but when it was about to freeze (I think) it started vibrating like crazy!! and then it rebooted

**Comment by StanNL** [comment]
That sure was very odd

**Comment by StanNL** [comment]
But maybe I just got called (I just realised I'm posting way too many comments, I'll fuse them into one)

**Comment by ghost** [comment]
@Mikahlo It didn't work for me, again. It sure is strange that it does work for you.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Mikahlo** [comment]
The benchmark needs a while. After that I reboot to see if this kernel boots consistent.

**Comment by Spookcity** [comment]
@Mikahlo The fact that it boots properly at all leads me to believe even stronger that it does have to do with voltage and ASV fusing. Why there would be differences between our phones is beyond me,but this is looking more and more likely to me.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Mikahlo** [comment]
Mkay it's a mess. It boots consistent but reboots randomly. The 1.7 step is not used at all and the settings app seems to hang if you scroll down in the "phone status" section.
![screenshot_20170617-183543](https://user-images.githubusercontent.com/28191436/27254631-5591169e-538c-11e7-8ab7-62738e6418d2.png)

**Comment by Spookcity** [comment]
@Mikahlo Weird,weird,weird. Oh well. I don't have anything else I can think of to try. Maybe I'll think of something,but it seems as if the 1.7 is a lost cause. Thanks again for testing everyone.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
Test 20, hung on the animation. The second time worked fine, even managed to get a message in WhatsApp and read it. Then the screen went off and the phone no longer turns on at all and does not react to charging. It seems burned down completely (

**Comment by Mikahlo** [comment]
@Oleggluk try holding down vol-, home and the power button for while

**Comment by Oleggluk** [comment]
He is very hot. I pulled out the battery and put everything in the refrigerator. A little later I'll try to turn it on.

**Comment by Spookcity** [comment]
@Oleggluk It is def differences in voltage/cpu steps or capabilities of our phones then. I am 90% sure of this at this point. Very strange that it's that way,but I truly believe it is now. Since it has to do (likely) with CPU steps and voltages,I will look at changing the 1.7 voltages if I'm able. Perhaps tomorrow. The 1.7 voltages are the same as the 1.6,but since it appears to be about "stepping" perhaps this could help.
I have been using the 1.7 OC for over a week now and have had 1 bizarre thing...A reboot after flashing gapps on RR.  

Whoa,I just read apparently something I missed..Your phone is broken? Man, err 
How the hell is this possible?! The voltages on test 20 are stock. This makes no sense. Uhg,I feel really really bad now,sh%$  

There is def some differences in CPU stepping/voltages between our phones. I am positive. I so hope that @Oleggluk phone will work again,man.
I think I will not play with the 1.7 any longer. Its a strange issue and I would love to understand why it works so well for me and not others,but not at the risk to anyone's phone.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
I inserted the battery, went twrp successfully, and restored the kernel backup. The phone works fine. Something is already terrible to experiment. Let the smartphone rest.

**Comment by Spookcity** [comment]
@Oleggluk whew, Amazing news. I am very glad! I agree,the 1.7 tests are done. I'm sure,for some odd reason, that its a difference in CPU stepping and voltages between our phones. Still very strange,but I am content to let it rest at that. I don't want to be the reason why anyone's phone breaks. Its not worth that at all!

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
The most interesting is that I use a custom kernel to save battery power, and not to overclock. I do not really need 1700, it was just interesting). I'd rather wait for a stable version of 1600 with new governors and voltage regulation).

**Comment by Mikahlo** [comment]
I'm back on the test 5 kernel and suggest to leave the 1.7 behind and concentrate on what's already working to improve things if possible.
sayonara

**Comment by Oleggluk** [comment]
@Mikahlo Test 9 and Test 13 are also stable.

**Comment by Spookcity** [comment]
@Oleggluk Hehe,yes. Well I appreciate you testing and I'm very very glad your phone is OK. I will only work on the 1.6 version (and just keep a 1.7 branch updated for personal use)
I have already added many new governors,IO shed,TCP congestions. I have also moved a particular CPU function to be inline with newer kernel versions 3.8 etc) This is important for getting certain CPU governors to work properly on our 3.4 kernel. I've also added alucard hotplug. Which was a bit of a hassle, but seems to work relatively well.
Either way,I'll try to get a (1.6) test build with some new stuff up on here real soon.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jimmy999x** [comment]
![image](https://user-images.githubusercontent.com/21678167/27256412-643d2324-538a-11e7-9795-a69268ca1ba2.png)
someone help me?

**Comment by Spookcity** [comment]
@jimmy999x  Hmm.interesting error. I have to assume you have this line in the BoardConfig.mk:
"BOARD_RECOVERYIMAGE_PARTITION_SIZE := 12582912" If so for some reason it is not being used I don't think. I'm unsure what would be causing this,sorry.

**Comment by w3bservice** [comment]
@jimmy999x
Es sieht so aus als wenn im makefile ein Aufruf steht und er Werte aus erwartet die nicht übrsetzt worden sind.
Schau Dir mal die audio_hw.c an. 

Solche Probleme hatte ich immer wenn ich mir den Seamonkey aus anderen repos über setzt habe. Meist ist es eine Abhängigkeit bzw unterschiedliche Lib-versionen.

**Comment by w3bservice** [comment]
@Spookcity
Kernel MM and your AEX 4.2 running good 
Thx

**Comment by Spookcity** [comment]
@w3bservice Interesting. I guess you mean the build in the XDA thread? I'm surprised this works for a 7.x based ROM honestly as a lot has changed for our kernel. Either way,glad it works. I'd recommended test 13 though for nougat. Only because, while having less features at this point. It is tweaked more already than the MM version

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by w3bservice** [comment]
@Spookcity
My mobile runs with AEX and Test9 and the mobile phone of my wife with CM13 and MM. There I was with the Fnger leg write faster than the thoughts, sorry. Hear is a old man at work :XD

**Comment by w3bservice** [comment]
@Spookcity
A bit of confusion keeps the hirsutes on the go

**Comment by Spookcity** [comment]
@w3bservice Haha,believe me I know the feeling :D

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity Today we will experiment?))

**Comment by Spookcity** [comment]
@Oleggluk Hah,nope :D Yesterday was enough. I'd think for you as well! Ya wanna test out 2000 MHZ?!  Hehe 
I'm not home now,but I plan to release test 13 as version 1 on XDA tomorrow or Tuesday. After that, hopefully late next week I will post a build up on here for test with some of the new features.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@Spookcity I've been thinking about 1.7GHz and I was wondering if you've already tried making a Marshmallow kernel with 1.7 GHz. I don't know if you still have the necessary files to do it, but it may be worth trying.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@StanNL Interesting idea. I do have everything I need. I actually just built a MM kernel this morning to put on the XDA thread.. I will build a 1.7 version tomorrow if you'd like to give it a test. There has been many kernel changes since MM. So who knows
@Oleggluk  is not allowed to test though :D hah

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
I now know why the CPU frequencies didn't do what I wanted: Whenever you turn the screen off, the CPU either goes into deep sleep or it uses 800 MHz. Interesting behaviour...

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Guntzog** [comment]
@Spookcity I used your kernel on the LOS latest build and it fixed the sim detecting problem, you allow me to post the solutions for them?

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@StanNL This makes sense. Nougat handles sleep and CPU idling differently then previous versions I believe. Plus I have applied a good deal (15+) patches for CPU idle and CPU scheduling for tweaking/problem solving. Plus doze. So the combo of these I'm sure is the reason. 

Edit:
I've added and have messed around some with alucard hotplug. I've never really used any hotplug governors,but you can choose minimum cores always online,max cores online and cores online with the screen off. It seems to be a nice battery saver. I plan to try to add more hotplug governors if able. It was more difficult to add than a "regular" governor,but hopefully I'll work it out.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
I'm here reading all the nonsense on the Internet and that's what I thought. Everyone knows that on our smartphone there was a regular FM radio on firmware 4.4.2, it was necessary to install apk. But then on 5.1.1 it stopped working. I read on the Internet that "mobile devices have a universal chip for Wi-Fi, Bluetooth and FM, but the company at the program level blocked the possibility of listening to radio stations." So, what is the probability for us to unlock FM?
More from the Internet: "Previously, cellular operators AT & T, Sprint, Blu and T-Mobile in the US agreed to activate the FM chip in mobile devices, Sprint has already enabled the function on contract Android-smartphones, and AT & T, Blu and T-Mobile are ready to do this in any time."
So this is possible in principle.

**Comment by ghost** [comment]
@Oleggluk If our phone's hardware is capable of receiving FM radio broadcasts, which is what you just claimed, it should indeed be possible. 
The only problem is the fact that installing an FM-radio.apk isn't enough. There's a lot more to it than just that, but I think @Spookcity is capable of doing it, given that Samsung provides the necessary means.
The FM radio also needs the appropriate libraries that often are device-specific and sometimes also (Android) version-specific. However, you also said that our device was able to use FM radio with Android KitKat. If that's true, the libraries should be available for our device and we __might__ be able to implement them into either Spookcity's kernel or as a separate flashable zip for our device. The problem is just the fact that a lot has changed since Android 4.4.2 and it is quite likely that the old libraries won't work anymore, but maybe there's a chance that we are able to modify them to work with Android N.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@Oleggluk Hmm,very interesting. I honestly have no idea if this is possible or not. It seems like it should be,but I could be very wrong. It's something I can look into at some point. It is interesting how it was blocked or what-not. I wonder why exactly.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@Spookcity They probably just felt like it wasn't worth the maintenance. Using FM radio would be cool though

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@StanNL Yeah, I think you're probably right. I can't really think of another reason. 
 
I also very much agree with your post about implementing FM radio. I don't know exactly how it is implemented, but like you said, if it was available on KK,the needed libraries should be available. 

Edit:
It may simply be enough to get the libs,have them flash/install along with my kernel and build the appropriate kernel module for it. As also mentioned by @StanNL though a lot has changed since KK, so fixing may be needed which becomes more difficult obviously.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by w3bservice** [comment]
@Spookcity
An FM radio would be class. Germany is about to ban the sale of new equipment. And when you look at what goes on here, everything fits into the paternalism of the citizens. I head back to the time of the GDR, just worse. Internet, restrict freedom of expression. I already knew that. But here no one does what. And now there is only digital radio. Nice, but it can be controlled who gets a license and sends system-conform. Orson Wells 1984 or V like Vandetta.

**Comment by Spookcity** [comment]
@w3bservice  I didn't know that about Germany. Interesting stuff. I will only say that 1984 is one of my favorite books of all time and V for Vendetta one of my favorite movies.

I am home earlier than expected. Therefor I am going to try to build the MM kernel OC'ed to 1.7

[Here's](https://drive.google.com/open?id=0B_rGv18gTmnVd3VpQ3J6VGRMLWM) the MM kernel OC'ed to 1.7. I have flashed this on Lineage 14.1 and it does indeed boot. I had an "android is starting" message on boot and it took a little bit for my sim and WiFi to be detected,but it works.
EDIT: there are def issues though with some apps. Either way,this is just to test the 1.7 OC,so not a big deal.

**Comment by ghost** [comment]
@Spookcity I tried using it on LineageOS 14.1 and it didn't work, but I'll try it with CM13.
EDIT: It did survive longer though. It actually lasted for about a minute, and then it froze again. 
EDIT 2: Maybe that means I can get a system log now.
EDIT 3: My old CM13 file seems to be corrupt, I'll try using it with XOSP 6.2 (based on Marshmallow)

**Comment by Spookcity** [comment]
@StanNL Thanks a lot for trying. Strange it didn't work for you on LOS 14.1. I'm typing from it now. Although there are issues. 

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@Spookcity XOSP gave me an error that there is no system volume, so therefore it cannot mount it, which is odd, but that doesn't mean it won't boot, right?
EDIT: It booted anyway. That was a strange error. I haven't installed the kernel yet so we'll have to wait for now.

**Comment by Spookcity** [comment]
@StanNL I have no idea honestly. Its weird that your having these problems. I can't really explain this.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
Yeah that was one of the strangest errors I've ever seen, but it's probably an XOSP bug.

**Comment by Spookcity** [comment]
@StanNL Haha, the your vs. you're is one of my pet peeves so I understand :D

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@Spookcity Would you like me to get a Marshmallow log or a Nougat log? (or no log at all)

**Comment by Spookcity** [comment]
@StanNL Prefer Nougat probably if possible,but either may be helpful.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@Spookcity Well I already made a Marshmallow log now, but I can make one for Nougat too if you want. Here's the Marshmallow one:
https://drive.google.com/open?id=0B1kigzj08bK2YU5uMWtWaTVUaGc

**Comment by Spookcity** [comment]
@StanNL All good. Thank you! I will try to have a look after I eat.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@Spookcity Sure! Take your time

**Comment by Spookcity** [comment]
F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x27e098 in tid 1941 (servicemanager)

F DEBUG   : pid: 1941, tid: 1941, name: servicemanager  >>> /system/bin/servicemanager <<<
F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x27e098
F DEBUG   :     #00 pc 00017838  /system/lib/libc.so (memcpy+212)
F DEBUG   :     #01 pc 0003f265  /system/lib/libc.so (strdup+24)
F DEBUG   :     #02 pc 0000474b  /system/lib/libselinux.so
F DEBUG   :     #03 pc 00000d9d  /system/bin/servicemanager
F DEBUG   :     #10 pc 000173b1  /system/lib/libc.so (__libc_init+44)
F DEBUG   :     #11 pc 00000c8c  /system/bin/servicemanager

Interesting,but I really don't see how this is related to the kernel. Plus @Mikahlo had a kernel oops in his log. So now were at 2 different things. I just don't know. There is a lot of stuff going on in that log though.

Edit: 
Sorry,Githubs markup language turns the numbers into links

Edit II:
Process com.android.cellbroadcastreceiver (pid 3272) has died
THis is the cause of that I believe.

Edit III:
Definitely cellbroadcastreciever
oadcastreceiver: type=1701 audit(0.0:224): auid=4294967295 uid=10004 gid=10004 ses=4294967295 subj=u:r:platform_app:s0:c512,c768 reason="memory violation" sig=11

**Comment by ghost** [comment]
@Spookcity I hope you understand that log better than I do...

I'll also get a Nougat log for you. Should I make a log with the normal kernel as well just for comparison?

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@StanNL yeah you def can do that if its no hassle. I just cant see how this is kernel related. Your system obviously crashed,we know that. We now know the reason,but where the heck does cellbroadcastreceiver come into play. Its very bizarre to me

**Comment by ghost** [comment]
@Spookcity The reason is "memory violation", but I have no clue why...

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@StanNL Yes,this seems to be the cause of signal 11's most of the time in my limited experience. Its the same reason Firefox was crashing the system recently with the kernel updates. I just cant imagine this is related to the kernel though

**Comment by ghost** [comment]
@Spookcity @Oleggluk @Mikahlo @tester-02 @jimmy999x Please continue at #20

**Comment by Igor9393** [comment]
Надеюсь у вас все получится
