### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by ghost** [Spookcity/ROMS-G800F#2]
The most important reason why we created this way of communication, is because we never knew when someone created a new ROM or posted an update to it.
Here, you can comment whenever you've made something you'd like to share.
 

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
A sample announcement would be:

_I updated XOSP to version 1.7. The most important change is the fact that it is now based on Android Nougat! You can download it [Here](hi)_ 

The full changelog should be at the specific topic for the ROM. (By the way, the message wasn't real, unfortunately)

**Comment by Spookcity** [comment]
I have updated Slim 7 from beta 0.16 -> beta 0.19
**Download the ROM**   - [Slim 7 Beta 0.19](https://www.androidfilehost.com/?fid=817550096634763570)
**XDA Thread**  - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-slim-rom-7-nougat-t3558926)
**Changelog** - [Changes](https://github.com/Spookcity/ROMS-G800F/issues/7#issuecomment-295824209)

**Comment by Spookcity** [comment]
I have updated AEX to Version 4.1!
**Download the ROM** - [AEX V4.1](https://www.androidfilehost.com/?fid=817550096634764064)
**XDA Thread** - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aospextended-rom-v3-3-t3573531)
**Changelog** - [Changes](https://github.com/Spookcity/ROMS-G800F/issues/11#issuecomment-296379462)

**Comment by ghost** [comment]
After a few days of getting this set up and figuring out how this works, I've finally found out how notifications on GitHub work.

> When you watch this repository, you'll get email notifications when new issues are created and new comments are posted. Make sure to do that so you'll never miss an announcement. 

> In those emails, there's a link that says "Mute this thread". When you don't want to get more emails on that specific topic, just click that link and you'll only get emails on the topics you're interested in! Or, more specific: you __won't__  get updates on topics you're __not__  interested in!


So you don't have to leave a comment on an issue in order to get email updates, but you can just watch this repository by clicking on the eye icon!

**Comment by Spookcity** [comment]
I have updated AICP to 7.1.2
**Download the ROM** - [AICP 7.1.2](https://www.androidfilehost.com/?fid=745425885120728320)
**XDA Thread** - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aicp-12-1-nougat-t3565009)
**Changelogs can be found in the "AICP Extras" app**

**Comment by Spookcity** [comment]
I have created a thread and uploaded XOSP 7.1.1 to XDA
**Download the ROM** - [XOSP 7.1.1](https://www.androidfilehost.com/?fid=817550096634766001)
**XDA Thread** - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-xosp-nougat-t3598829)

**Comment by Spookcity** [comment]
I have updated AOKP to 7.1.2
**Download the ROM** - [AOKP 7.1.2](https://www.androidfilehost.com/?fid=457095661767157922l)
**XDA Thread** - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aokp-nougat-t3570088/page4#post72117523)
**Changelogs can be found within the "ROM Control" app**

**Comment by Spookcity** [comment]
I have updated Beanstalk ROM to 7.1.2
**Download the ROM** - [Beanstalk 7.1.2](https://www.androidfilehost.com/?fid=529152257862724679)
**XDA Thread** - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-beanstalk-7-nougat-t3585327)
**Beanstalk Specific issues** - [Github](https://github.com/Spookcity/ROMS-G800F/issues/8)
**Changelogs can be found within settings -> about phone -> about beanstalk  -> beanstalk changelogs**

**Comment by Spookcity** [comment]
I have updated Slim 7 to beta 0.24
**Download the ROM**  [Slim 7.1.2 beta 0.24](https://www.androidfilehost.com/?fid=889764386195901081l)
**XDA Thread**  [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-slim-rom-7-nougat-t3558926)
**Changelogs** [Changes](https://github.com/Spookcity/ROMS-G800F/issues/7#issuecomment-303092649)

**Comment by Spookcity** [comment]
I have updated AEX to v4.2
**Download the ROM** [AEX 4.2](https://www.androidfilehost.com/?fid=817550096634771661)
**XDA Thread** [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aospextended-rom-v3-3-t3573531)
**Changelogs** [Changes](https://github.com/Spookcity/ROMS-G800F/issues/11#issuecomment-303733908)

**Comment by Spookcity** [comment]
I have updated AICP
**Download the ROM** [AICP 12.1](https://drive.google.com/open?id=0B_rGv18gTmnVVkZhby1zenRzbzg)
**XDA Thread** [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aicp-12-1-nougat-t3565009)
**Changelogs Can be founf within the ROM - Settings ->Aicp Extras -> Changelog**

**Comment by Spookcity** [comment]
I have updated AOKP
**Download the ROM** [AOKP 7.1.2.](https://www.androidfilehost.com/?fid=889764386195907565)
**XDA Thread** - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aokp-nougat-t3570088/page4#post72117523)
**Changelogs can be found within the "ROM Control" app**

**Comment by Spookcity** [comment]
I have updated Beanstalk ROM
**Download the ROM** - [Beanstalk 7.1.2](https://www.androidfilehost.com/?fid=817550096634780487)
**XDA Thread** - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-beanstalk-7-nougat-t3585327)
**Beanstalk Specific issues** - [Github](https://github.com/Spookcity/ROMS-G800F/issues/8)
**Changelogs can be found within settings -> about phone -> about beanstalk  -> beanstalk changelogs**

**Please see the main XDA post for an important note about this build**

**Comment by Spookcity** [comment]
I have (finally) created a thread and released my kernel on XDA. This is the exact same as test13 that was posted on here,so no need to flash if you are running that. I will now be creating test builds and posting them on here. Perhaps this weekend even as I have added and tweaked things a fair bit since this version.
[XDA](https://forum.xda-developers.com/galaxy-s5-mini/orig-development/kernel-spookcitykernel-n-7-x-custom-roms-t3626015)

**Comment by Spookcity** [comment]
I have updated AEX to Version 4.3
**Download the ROM** [AEX 4.3](https://www.androidfilehost.com/?fid=889764386195911916)
**XDA Thread** - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aospextended-rom-v3-3-t3573531)
**Changelog** [Changes](https://github.com/Spookcity/ROMS-G800F/issues/11#issuecomment-311387644)

**Comment by Spookcity** [comment]
I have updated Slim 7 from beta 0.24 -> stable 1.0
**Download the ROM**   - [Slim 7.1.2 - Stable 1.0](https://www.androidfilehost.com/?fid=817550096634782973l)
**XDA Thread**  - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-slim-rom-7-nougat-t3558926)
**Changelog** - [Changes](https://github.com/Spookcity/ROMS-G800F/issues/7#issuecomment-312433122)

**Comment by Spookcity** [comment]
I have updated AICP
**Download the ROM** [AICP 12.1](https://www.androidfilehost.com/?fid=817550096634785581)
**XDA Thread** [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aicp-12-1-nougat-t3565009)
**Changelogs Can be founf within the ROM - Settings ->Aicp Extras -> Changelog**

**Comment by Spookcity** [comment]
I have updated AOKP
**Download the ROM** [AOKP 7.1.2.](https://www.androidfilehost.com/?fid=817550096634787502)
**XDA Thread** - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aokp-nougat-t3570088/page4#post72117523)
**Changelogs can be found within the "ROM Control" app**

**Comment by Spookcity** [comment]
I have updated Beanstalk ROM to 7.1.2
**Download the ROM** - [Beanstalk 7.1.2](https://www.androidfilehost.com/?fid=889764386195919544)
**XDA Thread** - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-beanstalk-7-nougat-t3585327)
**Beanstalk Specific issues** - [Github](https://github.com/Spookcity/ROMS-G800F/issues/8)
**Changelogs can be found within settings -> about phone -> about beanstalk  -> beanstalk changelogs**

**Comment by Spookcity** [comment]
I have updated Slim 7 from version 1.0 -> 1.4
**Download the ROM**   - [Slim 7.1.2 - Stable 1.4](https://www.androidfilehost.com/?fid=745425885120753540)
**XDA Thread**  - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-slim-rom-7-nougat-t3558926)
**Changelog** - [Changes](https://github.com/Spookcity/ROMS-G800F/issues/7#issuecomment-320430984)

**Comment by Spookcity** [comment]
I've updated my kernel to v4.0. See the [XDA](https://forum.xda-developers.com/galaxy-s5-mini/orig-development/kernel-spookcitykernel-n-7-x-custom-roms-t3626015) thread for more details.

**Comment by Spookcity** [comment]
I have updated AEX to v4.5

**Download the ROM** [AEX 4.5](https://www.androidfilehost.com/?fid=961840155545588256)
**XDA Thread** [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aospextended-rom-v3-3-t3573531)
**Changelogs** [Changes](https://github.com/Spookcity/ROMS-G800F/issues/11#issuecomment-321973751)

**Comment by Spookcity** [comment]
I have updated AICP
**Download the ROM** [AICP 12.1](https://www.androidfilehost.com/?fid=961840155545591815)
**XDA Thread** [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aicp-12-1-nougat-t3565009)
**Changelogs Can be found within the ROM - Settings ->Aicp Extras -> Changelog**

**Comment by Spookcity** [comment]
I released v5.0 of my kernel on [XDA](https://forum.xda-developers.com/galaxy-s5-mini/orig-development/kernel-spookcitykernel-n-7-x-custom-roms-t3626015) It is the same as test version 4.0b. I fixed the voltage control on the 1500mhz version...I think.

**Comment by Spookcity** [comment]
I have updated AEX to v4.6. This is the final Nougat release.
**Download the ROM** [AEX 4.6](https://www.androidfilehost.com/?fid=745425885120763621)
**XDA Thread** [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aospextended-rom-v3-3-t3573531)
**Changelogs** [Changes](https://github.com/Spookcity/ROMS-G800F/issues/11#issuecomment-330436929)

**Comment by Spookcity** [comment]
I have updated AICP
**Download the ROM** [AICP 12.1](https://www.androidfilehost.com/?fid=961840155545597310)
**XDA Thread** [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aicp-12-1-nougat-t3565009)
**Changelogs Can be founf within the ROM - Settings ->Aicp Extras -> Changelog**

**Comment by Spookcity** [comment]
I have updated Slim 7 from version 1.4 -> 1.11
**Download the ROM**   - [Slim 7.1.2 - Stable 1.11](https://www.androidfilehost.com/?fid=745849072291676455)
**XDA Thread**  - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-slim-rom-7-nougat-t3558926)
**Changelog** - [Changes](https://github.com/Spookcity/ROMS-G800F/issues/7#issuecomment-332402582)

**Comment by Spookcity** [comment]
I have updated AOKP
**Download the ROM** [AOKP 7.1.2.](https://www.androidfilehost.com/?fid=817906626617936710)
**XDA Thread** - [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aokp-nougat-t3570088/page4#post72117523)
**Changelogs can be found within the "ROM Control" app**

**Comment by Spookcity** [comment]
I have done a fresh build of AEX 5.0 and created a thread on XDA 
[XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aospextended-rom-v5-0-t3696001)

**Comment by Spookcity** [comment]
I've updated Slim ROM to v 1.16. It is the final update.

**Download** [Slim 1.16](https://androidfilehost.com/?fid=962021903579490415)

**Changelogs can be found** [Here](https://slimroms.org/)

**Comment by Spookcity** [comment]
I've updated AEX 5.0. Details and download can be found on [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-aospextended-rom-v5-0-t3696001/page2#post74682228)
