### ISSUE TITLE
Questions/Advice about ROMs

### ISSUE THREAD

**Issue by ghost** [Spookcity/ROMS-G800F#3]
Are you unsure which ROM to choose or have you forgotten how to fix that camera bug everyone always talks about? Don't hesitate and ask it here.

**Comment by ghost** [comment]
I'll make a comparison of all the different available ROMs here, one day.


### LineageOS (CyanogenMod)

LineageOS is without a doubt the most famous ROM available and it is the successor to the well-known CyanogenMod after it was discontinued in 2016.
It is one of the most stable ROMs for our device and it is very close to stock Android. If you're new to ROMs, this one is definitely a safe choice because it is almost bug-free as far as I know.

__Availability__
- Android 6.0 = LineageOS 13.0
- Android 7.1 = LineageOS 14.1

__Maintainers:__ Hennymcc, ayke and zytrix78. Although __hennymcc__ is the official maintainer and he also makes all the edits to the device trees, ayke and zytrix78 make their own builds which only sync with sources.

### Validus/Tesla

This is one of the fewer ROMs that isn't available on XDA and therefore it isn't as popular as most ROMs, but you can find it at a Google+ community called "Ground Zero ROMs". I've attached links to both versions underneath this paragraph.
This might be the only custom ROM which has official support, but I think that this ROM even has less support than unofficial ROMs, so you shouldn't get too excited about that fact.
There are two versions for this ROM: Tesla and Validus. Tesla is the basic version with less customizability and fewer options, while Validus has "borrowed" a ton of features from other ROMs. Also: Tesla doesn't get as much support anymore since Validus was released, which is 4 months ago, so bugs like video zooming are still present, except on Validus. Therefore, I'd see no reason to choose Tesla, but Validus is a good ROM in my opinion.

They both do have OMS (substratum) support.


__Availability__
- [Validus (Android 7.1.1)](https://plus.google.com/+psyafter/posts/j3Rz2EdzBYi)
-  [Tesla (Android 7.1.1)](https://plus.google.com/+psyafter/posts/apvitQHSdZr)




### XOSP (Xperia Open Source Project)

I've been using this ROM for quite some time now (both 6.0 and the unreleased 7.1.1), and I can definitely say it's extremely fast and snappy! I'm truly amazed by this. That's almost all there is to say about this ROM, the speed is just amazing. I'm not a big fan of the user experience, which is based off of the UI that Sony Xperia phones use, but the fluidity definitely makes up for that. The battery life isn't amazing  either and the ROM has all the bugs which the Marshmallow ROMs had, since it hasn't been updated to Nougat (Edit: It is!). Besides, the UI isn't _that_ bad. (see screenshots)

__Marshmallow__ 

![](http://i.imgur.com/jt3GauZ.png)

![](http://i.imgur.com/ywRpXnZ.png)

__Nougat__ 

![](http://i.imgur.com/G23QkYa.png)

![](http://i.imgur.com/Yp3VpQw.png)


__Availability__

Thanks to Spookcity, it now has both a Marshmallow version (Android 6.0.1) and a Nougat version (Android 7.1.1)! 

__Downloads:__ [XOSP 6.0.1](goo.gl/4zwqvH) and XOSP 7.1.1 doesn't have an XDA thread yet, but I think we can expect it to come very soon, as the initial test build feels very stable.




__Maintainers:__ Basically nobody at this point, but that may change in the future. Edit: It did! Spookcity has built the XOSP Nougat ROM! His 



### Slim

Slim is based on [AOSP](source.android.com) and their goal is to be fast, stable and as bloat-less as possible. They also now have their own  theme engine in Slim7, but it is a strange collaboration (sort of?) with Substratum and we're unsure what the real purpose of it is.

The boot animations of both Slim6 and Slim7 are gorgeous, by the way!

__Availability__ 

- Slim6 is based on Android 6.0.1. [XDA link](goo.gl/lMGEjq)
- Slim7 is based on Android 7.1.2. [XDA link](goo.gl/Ts8cET)


__Maintainers:__ Spookcity. His XDA username is spookcity138!

### AEX
AOSP Extended is, like the name suggests, based on AOSP, but it has many cherry picked customization features from other ROMs. It has full OMs (Substratum) support! It has borrowed those features from ROMs like:
- DirtyUnicorns
- Slim
- ZephyrOS
- Bliss
- OmniROm


__Availability__ 

- It only has Android 7.1.1 and 7.1.2 versions as far as I know. You can download it on [XDA](goo.gl/QPkj89).

__Maintainers:__ Spookcity. His XDA username is spookcity138!

### BeanStalk

This ROM is based off of LineageOS, but I has added extra customizability features. Unlike most Lineage-based ROMs, the background color of the quicksettings panel isn't a strange brownish/gray color (#212121), but it has the correct vanilla Android color (#233832 or something).

__Availability__ 

- It only has Android 7.1.1 and 7.1.2 versions which are available on [XDA](goo.gl/79rH3Y).

__Maintainers:__ Spookcity. His XDA username is spookcity138!

**Comment by StanNL** [comment]
Could anyone help me with this? I'm pretty sure I've used all ROMs but I don't remember every detail

**Comment by Oleggluk** [comment]
The best and most customizable is RESURRECTION REMIX !!!

**Comment by Guntzog** [comment]
@Oleggluk is a huge fun of RR :p
My recommandations for a customizable, smooth, almost bugless and a (A-) battery : Resurrection Remix and AEX nougat

**Comment by ghost** [comment]
My personal preference goes out to XOSP and LiquidROM. I may be a very 'special' user, because I highly focus on speed. Therefore, XOSP is my favorite ROM at the time of writing. However, I'm not a big fan of the Sony-based UI, so I am currently using LiquidROM and I must say that I really like it. 

Edit: You can download LiquidROM from the Test Builds section. It is in Jimmy's first comment.

**Comment by Spookcity** [comment]
I liked liquidROM as well. It was nice and fast. I just can't get away from AEX for customization options and Slim for a faster,not much there type ROM. Those are my 2 favorites as of right now.

**Comment by Guntzog** [comment]
AEX is perfect for me too, specially the night light feature, i read a lot and it helps me.

**Comment by Spookcity** [comment]
@Guntzog I agree. I change ROMS a lot,but I always end up back to AEX. For me it is the best ROM as well.

**Comment by Pat750** [comment]
I used Candy ROM for a week and it's really smooth out of the box. In terms of custom options it's in the mid range like AEX or Xenon.
It has Magisk12, Substratum, K9 material and Tugabrowser (which I didn't like). The back button can be remapped.
It has no file manager and I think the old MM SystemUI colours.
Home button doesn't answer calls and the charging screen says ??/100 (when device is off). 
No option to stop apps to start at boot although there is a data protection setting, just a bit different than on other ROMs
Substratum works, but dark power menu I could only get with Swift Dark Theme.
So for my not very heavy use it's a pretty good ROM. Used original kernel and test9.

**Comment by pranshu179** [comment]
Feed back :- touch is not so smooth  and the screen shot is not perfectly run when I swipe my finger so status bar or up down button works so screen shot is not perfectly save and magisk is also have some minor problem
