### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [Spookcity/ROMS-G800F#5]
If you have a request of any form, post it here and if you're lucky, someone will have some time for you.

It could be something like a new ROM that is really missing at the moment and you really like it.

**Comment by Oleggluk** [comment]
Has anyone tried to build a Mokee OS? (Google Translate)

**Comment by Spookcity** [comment]
@Oleggluk I think perhaps I tried during the MM days. I could be wrong though. If so,obviously I had some problem with it that I couldn't solve back then.

**Comment by Oleggluk** [comment]
It's a pity!((  Reviews are interesting. Maybe if there is time, will you try? (Google translation)

**Comment by Spookcity** [comment]
@Oleggluk Well,in all honesty I had planned to be done building ROMS (excluding updates to most of my previous builds) I'm trying to build CosmicOS now as a request. Maybe sometime I could give it a go though.
Perhaps jimmy999x could build? 

I would just rather spend time working on my kernel at this point,but if he won't/can't build I may try at some point. Just no guarantees.

**Comment by Oleggluk** [comment]
CosmicOS is not an interesting firmware)). In any case, thanks. Kernel test 3 runs on RR, no problem) (google translation)

**Comment by Spookcity** [comment]
@Oleggluk I know nothing about CosmicOS honestly. I was just asked awhile ago and said I would try.
I'm glad to hear the test3 kernel is running well. Hopefully I'm going to mess with it some more this week.

**Comment by Oleggluk** [comment]
I did not understand anything, but it seems interesting))).
https://forum.xda-developers.com/apps/magisk/module-enable-sdcardfs-t3603375

**Comment by Spookcity** [comment]
@Oleggluk Hehe thanks, I always appreciate links about new things and ideas to implement. I don't know too much about it either, except that it's Google's replacement for FUSE. I read a bit about it some time ago. I will read through that thread more. I believe it can be implemented in the kernel,as this is how I originally stumbled upon SDcardFS. I think it's not so easy to implement currently though. I could also be wrong

**Comment by Oleggluk** [comment]
Which fingerprint sensor is installed in our phone? Are there any other new phones with the same sensor? And the official android 7. Is it possible to get out the libs of the fingerprint from there and make it to our phone? (Google Translate)

**Comment by Spookcity** [comment]
@Oleggluk I honestly have no idea about this. I can look into it at some point though.

**Comment by aykxt** [comment]
Could you please add support for Ambient Display? If I search it in settings it shows me an option but when I click on it shows me the high touch sensitivity option instead of Ambient Display...

**Comment by Spookcity** [comment]
@aykut78  Good to see you here! As far as ambient display...What ROM are you referring to because I know some have it. I personally don't really use it,so I don't know. I assume it would just be a matter of cherry-picking the appropriate commits to get it working though.

**Comment by aykxt** [comment]
@Spookcity I'm using LineageOS 14.1 (20170515)

**Comment by Spookcity** [comment]
@aykut78 Maybe try one of the Lineage based ROMS that jimmy999x has posted? A lot of these have added features and may have that. I really don't know. However, I don't build LOS as there are enough people already building.

**Comment by ghost** [comment]
@Spookcity Now that the OnePlus 5 has been launched, I heard that OnePlus has made OxygenOS open source. Does that mean you can now make an OxygenOS ROM? I'm not an expert, but they did include "build instructions" (for Marshmallow, but there's also a Nougat branch in there) in this repository: https://github.com/OnePlusOSS/android  

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@StanNL Hmm,interesting. Honestly I'm unsure. I do know that from looking at the branches that all of the N/7.x branches have a QC prefix,meaning for Qualcomm I imagine. This doesn't mean it wouldn't build for our device,but may make it more difficult. If I have some time perhaps I'll give it a go and see what happens. Or maybe @jimmy999x is willing to try with his super computer :D

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jimmy999x** [comment]
https://drive.google.com/open?id=0B6HnvpggPH_henUzeURuNF85Yjg @aykut78 xosp 7.1.2 have ambient display enabled by default

**Comment by ghost** [comment]
@Spookcity Ooh I though QC meant Quick Charge (which it does, but not in this context). If it does mean Qualcomm, that could lead to some problems indeed.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
I recently found a ROM named PixelROM and it looks really interesting: https://gitlab.com/GooglePixelROM
Does anybody know if it's possible to build this ROM for our device?
@Spookcity @jimmy999x

**Comment by Spookcity** [comment]
@StanNL Hmm,well I just had a quick look. I tried to view their manifest to see where they were pulling some of their repos to get an idea of how difficult it may be,but it seems to be empty...Which would make it impossible to build. I'll have a look on my laptop later when I'm at home. Perhaps it's a phone issue..or I'm just not that smart :D

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@Spookcity Alright well there's no need to hurry whatsoever. The kernel test v4.0a (that's the latest one right?) works perfectly fine for me by the way

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@StanNL Yeah,v4.0a is the latest kernel. Glad to hear its going well so far. Let me know if you have any issues.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@Spookcity It's still working great as ever!

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
