### ISSUE TITLE
Slim7

### ISSUE THREAD

**Issue by ghost** [Spookcity/ROMS-G800F#7]
Here you can share your experiences with Slim7. You can post this on [XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-slim-rom-7-nougat-t3558926) too, __but if it's a test build__  or you just somehow feel like giving feedback here instead, feel free to do so.

P.S: There is a [Slim6](https://forum.xda-forums.com/galaxy-s5-mini/development/rom-slim6-marshmallow-t3403003) version too, which is based on Android Marshmallow!

**Comment by Spookcity** [comment]
**Changes from the last build (0.16) to 0.19**

**Slim 0.19**
- Android version 7.1.2
- Android security patch April 5,2017
- Implement Proximity Wake, DM's need to enable per device
 - Replace Gallery2 with SnapdragonGallery
- frameworks/av: mediacodec: minijail: Enable exporting of policy files, camera: Ensure native handle isn't null before closing it ( **I have reverted this. It broke sound**)
- frameworks/base: Revert Emergency call button on Swipe lock Screen, KeyguardSimPinView: don't send dummy request to get remaining pin, keyguard: Allow disabling fingerprint wake-and-unlock
- frameworks/native: SF: HWC1: Propagate the OMAP_ENHANCEMENT flag, HWComposer: Use native FB format for HWC 1.1, Prevent FB de-allocation with HWC 1.1+
- vendor/slim: Update for Slim7 Beta 0.19, other fixes and updates

**Slim 0.18**

- Frameworks_opt_slim is now frameworks_slim
- build: Unbreak verity/FEC generation
- frameworks/base: QS Tile fixes, other fixes
- frameworks/opt/net/wifi: fix possible NPE, WifiStateMachine: Probe neighbours only when roaming, Revert IpReachabilityMonitor handling changes
- frameworks/slim: SlimRecents: Make multiwindow more robust
- hardware/samsung: audio: Split BT SCO media/incall paths
- vendor/slim: Update for Slim7 Beta 0.18, APN fixes

**Slim 0.17**

- SlimRecents: Don't show panel if pinning is enabled - SpiritCroc & Ezio
- bionic: Allow devices to force shim libs
- build: upstream from LineageOS
- fw/native: commonize WORKAROUND_BUG_10194508 flag
- hw/samsung: Upstream from LineageOS
- hw/audio-caf/msm8974: Upstream from LineageOS
- Camera2, Snap, Gallery2: Translation updates
- Gallery2: Make location perm truly optional
- Settings: Fix Misc/Overcounted battery stats and add Slim version to about phone
- system/core: Upstream from LineageOS
- vendor/slim: Updates to build, apns and extract utils

**Comment by ghost** [comment]
Looks great, thanks! (By the way: this is the ideal time to find out if email notifications work)

**Comment by Spookcity** [comment]
Just checked my email. Works great for me. Thanks for getting this set up. Its a good idea!

**Comment by ghost** [comment]
@Spookcity I'm glad you like it! Hopefully this will work out the way I though it would! 
By the way: you can reply to the GitHub mails with an email, in order to reply to the comment

**Comment by Spookcity** [comment]
**Slim 7 Changelog**
Changes from last build (0.19) to 0.24
**Note SlimLauncher was still broken,so I removed it and added Nova Launcher**

**0.24**

- art: runtime: support kryo for 32bit
- bionic: Add support for kryo
- fw/av: Revert AudioSessionInfo API Bug #164
- fw/base: Translation update, Add support for pause & resume Download manager
- fw/native: sensorservice: Fix orientation sensor for HAL's missing rotation vector sensor
- apps/Dialer: Translation update
- apps/Settings: Translation update
- apps/SlimLauncher: Translation update
- apps/Snap: Fix crash switching from back to front cam in video mode
- providers/DownloadProvider: Display download speed, Add support for pause and resume
- services/Telephony: Translation update
- system/bt: Do not include the trailing NULL from C-String in the SDP service name

**0.23**
- fw/base: Allow override battery capacity using props, Telecom: Fix order of arguments when creating details object
- hw/samsung: Allow power_hint_low_power to disable power save mode
- Update translations for device settings

**0.22**
- May security update (android-7.1.2_r8)
- Fix dialer crash when entering calling accounts (Dialer and codeaurora/telephony
- fw/av: Fix policy for ffmpeg
- fw/base: Various fixes from Xiaomi (LineageOS)
- hw/libhardware_legacy: wifi: Add firmware loader support for the non-LKM cases
- hw/samsung: Translations updates
- libcore: Fix 7.1.2 merge conflict
- apps/Bluetooth: Revert handle opening incoming apk files and update translations
- vendor/slim: Cleanup repo, removing obsolete calls and overlays

**0.21**
- frameworks/base: Fixes to SystemUI, Bluetooth and WIFI
- frameworks/opt/telephony: General fixes for CMDA devices
- hw/libhardware_legacy: wifi: Change USES_TI_MAC80211 to a BoardConfig flag
- hw/samsung: Upstream from LineageOS
- hw/qcom/audio-caf/msm8916: Upstream from LineageOS
- hw/qcom/audio-caf/msm8996: Upstream from LineageOS
- packages/apps/Camera2: Translation update
- packages/apps/Snap: Translation update and other fixes
- system/bt: fix build for non-BLE after 7.1.2 merge
- vendor/slim: Update for Slim7 Beta 0.21

**0.20**
- Merge android-7.1.2_r2
- New color picker
- Enable AOSP Night mode (blue light filter)
- Disable full screen keyboard
- Fix battery alignment
- Cleanup SlimSettings for tablets
- bionic: Update from LineageOS
- frameworks/av: Upstream from LineageOS
- frameworks/native: Upstream from LineageOS
- frameworks/base: Updates to fingerprint, zygote
- hw/samsung: Upstream from LineageOS
- hw/qcom/audio-caf/msm8916: Upstream from LineageOS
- hw/ril & ril-caf: Fix crash when enabling RILC_LOG
- apps/Bluetooth: Upstream from LineageOS
- apps/Snap: Upstream from LineageOS
- system/extras: Updates to verity_verifyer (lineageOS)
- vendor/slim: Import CM charger, minor fixes for darwin building

**Comment by Spookcity** [comment]
**Slim 7 Changelog**
Changes from the last build (0.24) to stable 1.0

**0.29**
- device/qcom/common: Use correct opcode for STOE_CLK_SCALE_DIS
- fw/base: Upstream fixes from master, Add null check for action bar
- hw/qcom/display-caf/msm8916 msm8974: hwcomposer: Fix regression in hwc_sync
- hw/qcom/display-caf/msm8994: hwcomposer: Fix regression in hwc_sync, libmemtrack: Fix integer overflow in kgsl function, Fix duplicate copy file rules
- hw/qcom/media-caf/msm8994: vdec:Do not call stream_off on input port if all EBD's are not flushed.
- hw/ril ril-caf: fix a memory leak.
- hw/samsung: Add BLN support, Fix fast blinking notification LEDs, exynos: multimedia: add support for OMX_IndexParamVideoIntraRefresh parameter
- apps/Nfc: make T3T/Nfc-F HCE options
- apps/Snap: Upstream from LineageOS
- providers/MediaProvider: New material icon, Fix where condition of delete queries
- system/core: fix healthd include paths, Init: Run restorecon_recursive asynchronously
- Update sensitive phone # for BR, PT, GB and FR. Add Virgin Media Ireland to APN's

**0.28**
- Fix SlimDoze triggers not following Ambient Display
- Expose more resources for OMS
- fw/base: Minor fixes and optimizations
- Snap: Simulate back button when menu button is pressed, Add orientation correction for landscape -
 devices, Sign with platform keys
- system/bt: Disable AVRCP 1.6
- Add sensitive phone # for Israel

**0.27**
- Merge June security update (android-7.1.2_r17)
- Translation updates
- Updates to battery stats counter reset
- hw/qcom/audio-caf (msm8916 & msm8996): Upstream from LineageOS
- hw/qcom/media-caf (msm8916 & msm8996): Upstream from LineageOS
- hw/samsung: Upstream from LineageOS
- system/core: Updates to sched_policy
- Updates to sensitive phone numbers

**0.26**
- SlimDoze: Add handwave, pocket mode and tilt gesture (device dependant)
- Hide sensitive phone numbers from dialers - from LineageOS
- fw/slim: Fix screen off gesture action
- hw/samsung: Upstream from LineageOS
- stagefright-plugins: FFmpegExtractor: Don't use our extractor when we agree with StageFright
- apps/Snap: Upstream from LineageOS
- vendor/slim: Show full alarm info, Use aosp wallpaper croper, Enable Wi-Fi by default (fixes setupwizard fc)

**0.25**
- hw/samsung: Translation update
- apps/Snap: Translation update
- apps/SnapdragonGallery: Dark theme
- system/sepolicy: Allow recovery to alter / on userdebug/eng builds
- vendor/slim: Update lunch list, Extract_utils: fix extracting XML files containing binary characters, Fix text relocation warnings (keep default REL for PLATFORM_VERSION_CODENAME)

**Comment by Spookcity** [comment]
**Slim 7 Changelog**
Changes from the last build (1.0) to 1.4

**1.4**

- Fixed the APN issue (needing to manually enter APN information)
- fw/base: PowerProfile: allow overriding default power profile
- hw/qcom/fm: Update colors and translations (LineageOS)
- apps/Bluetooth: Translation updates (LineageOS)
- apps/Settings: MSIM: Fix user set DDS sub in hotswap cases.
- apps/Snap: Translation updates (LineageOS)
- resources/devicesettings: Translations update (LineageOS)
- vendor/qcom/opensource/dataservice : datatop: Fix out_dir array empty content verification. datatop: -
- Remove unused variables from datatop_ip_table_poll.c
- vendor/slim: Updates to APNs, sensitive phone numbers, offline charging graphics and build configs

**1.3**

- Translation updates
- bootable/recovery: Updater: Allow devices to supress BLKDISCARD
- fw/base: ScreenCap: Add support for jpeg. Bootreceiver: check console-ramoops-0
- fw/native: Updates to surface flinger (Upstream from LineageOS
- hw/qcom/fm: Upstream from LineageOS
- hw/samsung: Updates to power and secril (upstream from LineageOS)
= apps/Snap: Upstream from LineageOS

**1.2**

- Merge android-7.1.2_r23
- Fix default notification, alarm and ringtones Bug: #318
- fw/base: Reduce the setTransactions. SystemUI: Fix Notification Background Color Issue
- hw/qcom/audio: hal: add missing incall recording usecases and check
- hw/samsung: Upstream from LineageOS
- apps/Snap: Add overlay for restarting camera preview for additional cameras
- system/core: fs_mgr healthd: check console-ramoops-0. init.rc: setup console-ramoops-0. logcat: Add missing newline to read failure

**1.1**

- MusicFX: Updates and changes from CAF, Omni, DU and AospExtended
- Add Ambient Display QS tile
- Sensitive numbers: Update MCC codes
- stagefright-plugins: Fix 'supported' typo in log
f- w/av: CameraService: fix cameraId type of onDeviceStatusChanged
- hw/qcom/audio-caf/msm8916: Merge tag 'LA.UM.5.5.r1-04900-8x96.0' into HEAD
- hw/qcom/bt-caf: Merge tag 'LA.UM.5.5.r1-04900-8x96.0' into HEAD
- hw/qcom/fm: Update translations
- hw/qcom/keymaster: Add msm8996 and msm8998 into support list
- apps/Snap: Update translations
- services/Telecomm: SensitivePhoneNumbers: Handle lists of MCC codes
- Update APN's for China Telecom Macau
- misc build changes

**Comment by Spookcity** [comment]
**Slim 7 Changelog**
Changes from the last build (1.4) to 1.11

**1.11**

- fw/base: Don't disable GPS prematurely
- fw/base: PrivateStorageInfo: Exclude primary physical volume total space
- hw/qcom/audio-caf/msm8916: Merge caf/LA.BR.1.2.9_rb1.24
- hw/qcom/audio-caf/msm8974: aenc-aac: bounds checking
- hw/qcom/media-caf/msm8916: Merge caf/LA.BR.1.2.9_rb1.23
- hw/qcom/media-caf/msm8974: mm-video-v4l2: venc: Protect buffer from being freed while accessing
- apps/Snap: WideAnglePanoramaUI: Show switcher on Stop Captur

**1.10**

- framework/av: omx: Skip the whole dataspace signaling on legacy QCOM
- packages/apps/Snap: fix highspeed and high-framerate video recording
- packages/apps/Snap: fix ArrayIndexOutOfBoundsException on setUpCameraOutputs
- Additional translations: fw_base fw_slim Settings SlimLauncher Dialer Telephony

**1.9**

- fw/base: Use systemClock.elapsedRealtime() to calculate TTFF
- fw/base: Keyguard: Change fingerprint listening behavior
- hw/qcom/audio-caf/msm8998: Extend platform parser to allow device name aliasing
- apps/CellBroadcastReceiver:General updates and fixes from LineageOS

**1.8**

- fw/base: Audioservice set BT_SCO status. Camera: Ignore torch status update for aux or composite camera. Camera2: Fix error callback if buffer is lost
- hw/qcom/bt-caf: Revert Merge tag 'LA.UM.5.5.r1-04900-8x96.0' into HEAD
- apps/Bluetooth: Directly inform Audio HAL regarding SCO state change
- apps/Dialer: IMS-VT: Transmit static image when multitasking
- apps/Snap: Automatic translation import
- codeaurora/telephony: IMS-VT: Add config that controls visibility of static Image UI
- vendor/slim: Updates to Tmo US APN, other misc build environment changes

**1.7**

- frameworks/av: Camera: Add null checks on mdevice to avoid crash
- frameworks/base: SEEMP: Add auth framework for outgoing sms messages. Audioservice: Set BT_SCO status. Camera: ignore torch status updates for aux or composite camra. Camera2: Fix error callback if buffer lost.
- frameworks/native: SF: Improve hwrotation handling. Native: Increase art heap limit to 192MB for 1024MB ram devices
- hardware/broadcom/wlan: Merge tag android-7.1.2_r28
- hardware/qcom/bt-caf: libbt-qcom: Allow reading BT address from property. Revert 'Merge tag 'LA.UM.5.5.r1-04900-8x96.0' into HEAD'
- hardware/samsung: wifiloader: load kernel module if present
- apps/Settings: Revert 'Settings[Wifi]: fix the input invalid length for WEP encryption.'
- apps/Snap: Add missing null check on isCamera2Supported
- Updates to Correios Celular (BR) APN
- Updates to build environment

**1.6**

- Merge android-7.1.2_r29
- hw/qcom/fm: Upstream LineageOS
- hw/samsung: Upstreamfrom LineageOS
- apps/Bluetooth: Translation updates
- resources/devicesettings: Translation updates
- Add WOM internet/mms APN

**1.5**

- hw/samsung: Updates to power, secril and macloaders
- apps/Dialer: Fix compilation warnings
- apps/Snap: Fix low resolution front camera icon
- Updates to sensitive phone numbers
